variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

test-py27:
  stage: test
  image: python:2.7
  script:
    - pip install tox
    - tox -e py27

test-py35:
  stage: test
  image: python:3.5
  script:
     - pip install tox
     - tox -e py35

test-py36:
  stage: test
  image: python:3.6
  script:
    - pip install tox
    - tox -e py36

test-py37:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e py37

# only tagged releases
publish:
  stage: publish
  image: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_NAME}
  only:
    - /^v\d+\.\d+\.\d+$/  # eg. "v1.2.3", "v1.0.12" etc.
  except:
    - branches
  environment:
    name: pypi
  script:
    - python /src/bamp/setup.py sdist bdist_wheel -d /src/bamp/dist
    - twine upload /src/bamp/dist/*
