variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test-py27
  # - test-py35
  # - test-py36
  - coverage
  - publish

build:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_IMAGE:latest
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME -t $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CONTAINER_IMAGE:latest

test-py27:
  stage: test-py27
  image: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_NAME}
  script:
    - tox -c /src/bamp -e py27

coverage:
  stage: coverage
  image: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_NAME}
  script:
    - tox -c /src/bamp -e coverage

# add other python version tests

# only tagged releases
publish:
  stage: publish
  image: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_NAME}
  only:
    - /^v\d+\.\d+\.\d+$/  # eg. "v1.2.3", "v1.0.12" etc.
  except:
    - branches
  environment:
    name: pypi
  script:
    - python /src/bamp/setup.py sdist bdist_wheel -d /src/bamp/dist
    - twine upload /src/bamp/dist/*
